name: "traefik-compose"
services:
  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.leresolver.acme.httpChallenge.entryPoint=web"
      - "--certificatesResolvers.leresolver.acme.email=georgiy.guse@gmail.com"
      - "--certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.leresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory" # staggin сервер

    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.kowlad.ru`)"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=leresolver"
      - "traefik.http.services.dashboard.loadbalancer.server.scheme=https"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  #
      - "./letsencrypt:/letsencrypt"
    environment:
      - "TZ=Europe/Moscow"
    restart: unless-stopped

networks:
  traefik:
    name: "traefik-network"
    driver: bridge
