name: "service-boilerplate"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVICE_NAME: todo-api
      SERVICE_VERSION: v1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-https.rule=Host(`backend.kowlad.ru`) && PathPrefix(`/todo-api/v1`)"
      - "traefik.http.routers.backend-https.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      - "traefik.http.routers.backend.entrypoints=web"
#      - "traefik.http.routers.backend.entrypoints=websecure"
#      - "traefik.http.routers.backend.tls=true"
#      - "traefik.http.routers.backend.tls.certresolver=leresolver"
#      - "traefik.http.services.backend.loadbalancer.server.scheme=https"

    networks:
      - traefik
networks:
  traefik:
    name: "traefik-network"
    external: true