name: "service-boilerplate"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVICE_NAME: todo-api
      SERVICE_VERSION: v1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.goida.dev`) && PathPrefix(`/todo-api/v1`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=leresolver"
    networks:
      - traefik
    restart: unless-stopped
networks:
  traefik:
    name: "traefik-network"
    external: true